import { useState } from 'react';
import {
  X, Download, Mail, Copy, CheckCheck, FileText,
  CalendarDays, ChevronDown, ChevronUp, ExternalLink,
} from 'lucide-react';
import { pdf } from '@react-pdf/renderer';
import type { Schedule, ScheduledActivity } from '../../lib/types';
import { spell } from '../../lib/spelling';
import { generateICS, googleCalendarUrl } from '../../lib/icsGenerator';
import SchedulePDF from './SchedulePDF';

interface ExportModalProps {
  schedule: Schedule;
  activities: ScheduledActivity[];
  onClose: () => void;
}

// ── Plain text builder ────────────────────────────────────────────────────────

function buildPlainText(schedule: Schedule, activities: ScheduledActivity[]): string {
  const startDate = new Date(schedule.start_date + 'T00:00:00');
  const startLabel = startDate.toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' });
  const score = (v: number | null) => v === null ? '—' : String(v);

  const lines = [
    `BLOOM — My 10-Day ${spell.programme}`,
    `Started: ${startLabel}`,
    `Exported: ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}`,
    '', '─'.repeat(48), '',
  ];

  for (let day = 1; day <= 10; day++) {
    const dayDate = new Date(startDate);
    dayDate.setDate(dayDate.getDate() + day - 1);
    const dayLabel = dayDate.toLocaleDateString('en-AU', { weekday: 'short', day: 'numeric', month: 'short' });
    lines.push(`Day ${day}  ·  ${dayLabel}`);

    const acts = activities.filter(a => a.day_number === day);
    if (acts.length === 0) {
      lines.push('  (no activity planned)');
    } else {
      for (const a of acts) {
        lines.push(`  ${a.activity_name}  [${a.scheduled_time}]${a.category ? `  · ${a.category}` : ''}`);
        const hasPre  = a.pre_achievement  !== null || a.pre_connection  !== null || a.pre_enjoyment  !== null;
        const hasPost = a.post_achievement !== null || a.post_connection !== null || a.post_enjoyment !== null;
        if (hasPre)  lines.push(`  Expected  A:${score(a.pre_achievement)}  C:${score(a.pre_connection)}  E:${score(a.pre_enjoyment)}`);
        if (hasPost) lines.push(`  Actual    A:${score(a.post_achievement)}  C:${score(a.post_connection)}  E:${score(a.post_enjoyment)}`);
        if (a.completed) lines.push('  ✓ Completed');
        if (a.notes) lines.push(`  Notes: ${a.notes}`);
      }
    }
    lines.push('');
  }

  lines.push('─'.repeat(48));
  const completed = activities.filter(a => a.completed).length;
  lines.push(`Total completed: ${completed} of ${activities.length} planned`);
  lines.push('', 'Generated by Bloom — behavioural activation');
  return lines.join('\n');
}

// ── Platform badge ────────────────────────────────────────────────────────────

function PlatformBadge({ label, detail }: { label: string; detail: string }) {
  return (
    <div className="flex items-start gap-2.5 py-2.5 border-b border-[#EDE8E0] last:border-0">
      <div className="w-5 h-5 mt-0.5 rounded-md bg-[#EDE8E0] flex items-center justify-center shrink-0">
        <span className="text-[9px] font-bold text-[#5C5A57]">
          {label.slice(0, 1)}
        </span>
      </div>
      <div>
        <p className="text-xs font-semibold text-[#3D5A4C]">{label}</p>
        <p className="text-xs text-[#8A8680] leading-relaxed">{detail}</p>
      </div>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function ExportModal({ schedule, activities, onClose }: ExportModalProps) {
  const [email, setEmail] = useState('');
  const [copied, setCopied] = useState(false);
  const [generatingPdf, setGeneratingPdf] = useState(false);
  const [showPlatformGuide, setShowPlatformGuide] = useState(false);
  const [showGoogleList, setShowGoogleList] = useState(false);

  const completed = activities.filter(a => a.completed).length;

  const startDate = new Date(schedule.start_date + 'T00:00:00');
  const endDate   = new Date(startDate);
  endDate.setDate(endDate.getDate() + 9);
  const fmtShort = (d: Date) => d.toLocaleDateString('en-AU', { day: 'numeric', month: 'short' });
  const dateRange = `${fmtShort(startDate)} – ${fmtShort(endDate)}`;

  // ── Handlers ────────────────────────────────────────────────────────────────

  const handleDownloadICS = () => {
    const ics = generateICS(schedule, activities, spell.programme);
    const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bloom-${spell.programme.toLowerCase()}-${schedule.start_date}.ics`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    setGeneratingPdf(true);
    try {
      const blob = await pdf(
        <SchedulePDF schedule={schedule} activities={activities} />
      ).toBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `bloom-${spell.programme.toLowerCase()}-${schedule.start_date}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setGeneratingPdf(false);
    }
  };

  const handleDownloadTxt = () => {
    const text = buildPlainText(schedule, activities);
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bloom-schedule-${schedule.start_date}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleEmail = () => {
    if (!email.trim()) return;
    const text = buildPlainText(schedule, activities);
    const subject = encodeURIComponent(`My Bloom ${spell.programme}`);
    const body = encodeURIComponent(text.slice(0, 1800) + (text.length > 1800 ? '\n\n[Download the full version for the complete schedule]' : ''));
    window.open(`mailto:${encodeURIComponent(email.trim())}?subject=${subject}&body=${body}`);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildPlainText(schedule, activities));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // ── Render ──────────────────────────────────────────────────────────────────

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
      <div className="bg-[#FAF6F0] rounded-2xl shadow-2xl w-full max-w-md border border-[#DDD8D0] max-h-[90vh] flex flex-col">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#DDD8D0] bg-white rounded-t-2xl shrink-0">
          <div>
            <h2 className="font-semibold text-[#2A3D32]">Save your {spell.programme.toLowerCase()}</h2>
            <p className="text-xs text-[#ABA8A3] mt-0.5">{completed} of {activities.length} activities completed</p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-[#F0EBE3] text-[#9E9B97]">
            <X size={18} />
          </button>
        </div>

        <div className="overflow-y-auto flex-1 p-6 space-y-5">

          {/* ── PDF (primary) ─────────────────────────────────────────── */}
          <div>
            <p className="text-xs font-semibold text-[#3D5A4C] uppercase tracking-wide mb-2">Recommended</p>
            <button
              onClick={handleDownloadPdf}
              disabled={generatingPdf}
              className="w-full flex items-center justify-between px-5 py-4 rounded-xl bg-[#3D5A4C] text-white hover:bg-[#2A3D32] disabled:opacity-60 transition-all group"
            >
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 bg-white/15 rounded-lg flex items-center justify-center">
                  <Download size={17} />
                </div>
                <div className="text-left">
                  <p className="font-semibold text-sm">Download as PDF</p>
                  <p className="text-xs text-[#A8C8B0]">
                    {generatingPdf ? 'Generating…' : 'Schedule, ACE scores, progress notes'}
                  </p>
                </div>
              </div>
              {generatingPdf
                ? <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                : <Download size={15} className="opacity-60 group-hover:opacity-100 transition-opacity" />
              }
            </button>
          </div>

          <div className="flex items-center gap-3">
            <div className="flex-1 h-px bg-[#E8E3DB]" />
            <span className="text-xs text-[#ABA8A3]">or</span>
            <div className="flex-1 h-px bg-[#E8E3DB]" />
          </div>

          {/* ── CALENDAR ──────────────────────────────────────────────── */}
          <div>
            <p className="text-xs font-semibold text-[#3D5A4C] uppercase tracking-wide mb-2">Add to calendar</p>

            {/* ICS download */}
            <button
              onClick={handleDownloadICS}
              className="w-full flex items-center justify-between px-5 py-4 rounded-xl bg-white border-2 border-[#EDE8E0] hover:border-[#7D9B76] hover:bg-[#F2F7F1] transition-all group"
            >
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 bg-[#EDE8E0] group-hover:bg-[#D8EDD8] rounded-lg flex items-center justify-center transition-colors">
                  <CalendarDays size={17} className="text-[#3D5A4C]" />
                </div>
                <div className="text-left">
                  <p className="font-semibold text-sm text-[#3D5A4C]">Download .ics file</p>
                  <p className="text-xs text-[#8A8680]">{activities.length} events · {dateRange}</p>
                </div>
              </div>
              <Download size={15} className="text-[#ABA8A3] group-hover:text-[#7D9B76] transition-colors" />
            </button>

            {/* Works with chips */}
            <div className="flex items-center gap-2 mt-3 px-1">
              {[
                { name: 'Apple Calendar', color: '#E8E3DB', text: '#3D5A4C' },
                { name: 'Google Calendar', color: '#D8EDD8', text: '#2D5A3A' },
                { name: 'Outlook',         color: '#DCE8F5', text: '#1A3A6B' },
              ].map(p => (
                <span
                  key={p.name}
                  className="px-2.5 py-1 rounded-lg text-xs font-semibold"
                  style={{ background: p.color, color: p.text }}
                >
                  {p.name}
                </span>
              ))}
            </div>

            {/* How-to guide toggle */}
            <button
              onClick={() => setShowPlatformGuide(o => !o)}
              className="flex items-center gap-1.5 mt-2 px-1 text-xs text-[#7D9B76] hover:text-[#3D5A4C] transition-colors"
            >
              {showPlatformGuide ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
              How to import on each platform
            </button>

            {showPlatformGuide && (
              <div className="mt-2 bg-white border border-[#EDE8E0] rounded-xl px-4 py-1 divide-y divide-[#EDE8E0]">
                <PlatformBadge
                  label="Apple Calendar (iOS / macOS)"
                  detail="Tap the downloaded file. Your calendar app opens automatically and asks to import."
                />
                <PlatformBadge
                  label="Google Calendar"
                  detail="Open Google Calendar › Settings › Import › choose the .ics file › Import."
                />
                <PlatformBadge
                  label="Outlook"
                  detail="Open the .ics file directly, or go to File › Open & Export › Import/Export."
                />
              </div>
            )}

            {/* Google Calendar individual event links */}
            {activities.length > 0 && (
              <>
                <button
                  onClick={() => setShowGoogleList(o => !o)}
                  className="flex items-center gap-1.5 mt-2 px-1 text-xs text-[#7D9B76] hover:text-[#3D5A4C] transition-colors"
                >
                  {showGoogleList ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
                  Or add events to Google Calendar one by one
                </button>

                {showGoogleList && (
                  <div className="mt-2 bg-white border border-[#EDE8E0] rounded-xl overflow-hidden divide-y divide-[#EDE8E0]">
                    {activities.map(act => {
                      const d = new Date(act.scheduled_date + 'T00:00:00');
                      const dayLabel = d.toLocaleDateString('en-AU', { weekday: 'short', day: 'numeric', month: 'short' });
                      return (
                        <a
                          key={act.id}
                          href={googleCalendarUrl(act)}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center justify-between px-4 py-3 hover:bg-[#F0F7EE] transition-colors group"
                        >
                          <div className="min-w-0">
                            <p className="text-xs font-semibold text-[#2A3D32] truncate">{act.activity_name}</p>
                            <p className="text-xs text-[#8A8680]">Day {act.day_number} · {dayLabel} · {act.scheduled_time}</p>
                          </div>
                          <ExternalLink size={13} className="shrink-0 text-[#ABA8A3] group-hover:text-[#7D9B76] transition-colors ml-3" />
                        </a>
                      );
                    })}
                  </div>
                )}
              </>
            )}
          </div>

          {/* ── Email ─────────────────────────────────────────────────── */}
          <div>
            <p className="text-xs font-semibold text-[#3D5A4C] uppercase tracking-wide mb-2">Email to yourself</p>
            <div className="flex gap-2">
              <input
                type="email"
                placeholder="your@email.com"
                value={email}
                onChange={e => setEmail(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleEmail()}
                className="flex-1 px-3 py-2.5 border-2 border-[#EDE8E0] rounded-xl text-sm bg-white focus:outline-none focus:border-[#7D9B76] placeholder:text-[#C4BFB8]"
              />
              <button
                onClick={handleEmail}
                disabled={!email.trim()}
                className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-[#7D9B76] text-white font-semibold text-sm hover:bg-[#5C7A55] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
              >
                <Mail size={15} />
                Send
              </button>
            </div>
            <p className="text-xs text-[#ABA8A3] mt-1.5">Opens your mail app with the schedule as text</p>
          </div>

          {/* ── Copy / .txt ───────────────────────────────────────────── */}
          <div className="flex gap-2 pt-1">
            <button
              onClick={handleCopy}
              className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl border-2 border-[#EDE8E0] bg-white text-[#3D5A4C] text-sm font-medium hover:border-[#7D9B76] transition-colors"
            >
              {copied ? <CheckCheck size={14} className="text-[#7D9B76]" /> : <Copy size={14} />}
              {copied ? 'Copied!' : 'Copy text'}
            </button>
            <button
              onClick={handleDownloadTxt}
              className="flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl border-2 border-[#EDE8E0] bg-white text-[#3D5A4C] text-sm font-medium hover:border-[#7D9B76] transition-colors"
            >
              <FileText size={14} />
              Download .txt
            </button>
          </div>

        </div>
      </div>
    </div>
  );
}
